### ISSUE TITLE
"Naming things"

### ISSUE THREAD

**Issue by jelrikvh** [e-ig/standards#1]
Please be advised there already is an organisation defining standards that are called "PSR": https://github.com/php-fig/fig-standards

I am aware that some say naming things is the hardest part of our jobs, but duplicating this name will only confuse the people you are trying to help. I urge you to choose a different name. Or even better, to propose such standards to be part of the already existing line of PSRs maintained by the PHP Interoperability Group as mentioned above.

(Note: I am not in any way affiliated with the PHP-FIG.)

**Comment by mmoreram** [comment]
HI there!

Thanks for your feedback. I am completely aware about the PSR naming, so I complete agree your comment.

> Anyone knows what the acronym PSR means?

We'll try to find another name instead :)

Thanks!

**Comment by jelrikvh** [comment]
Yay :+1:
And another :+1: for the quick response.

**Comment by mmoreram** [comment]
As the second part of my response...

> Or even better, to propose such standards to be part of the already existing line of PSRs
> maintained by the PHP Interoperability Group as mentioned above.

We're talking about E-commerce related interfaces. PHP-FIG is focused on common implementations for all PHP projects. How would you fit a Money standard into it? It has no sense. FIG is too common (and necessarily common, btw) so the purpose of this group is to focus only on E-commerce-related problems :)

**Comment by jelrikvh** [comment]
Fair enough and that's fine. As long as the names do not collide, I don't think there will be any confusion :-).

**Comment by skoop** [comment]
I applaud standardization, as it prevents NIH syndrome, so :+1: on this effort. I'm not sure I fully agree with the reason not to go with the FIG, since even non-e-commerce projects could benefit from things like a Money standard or similar things. Perhaps at least a collaboration is possible, so that people will be able to know about these standards and benefit from them, even if they are not in FIG.

**Comment by mmoreram** [comment]
@skoop Of course, all standards from this group will be usable from any kind of project. The most positive part of splitting both groups is that each group will host different professionals focused on their strengths. E-IG group should host all E-commerce leaders, so all discussions should be E-commerce-first. Of course, FIG should do what have been doing properly for the last years :)
