### ISSUE TITLE
Members list - Website information missing ?

### ISSUE THREAD

**Issue by nyamsprod** [e-ig/standards#2]
This is a great initiative. But what will be its impact if we can not name the e-commerce solutions who are backing this initiative.One of the reasons the PHP-FIG gain so much traction is because we know as developers that frameworks like Zend, Symfony, Laravel for examples are active members. 

Right now even if I wanted to promote your group to fellow developers or to potential e-commerce solutions  I wouldn't know where to start as no listing of members seem to exist.

You should advertise this e-ig initiative through at least a simple website with a list of members. Even if they are few to start with. This would give an indication of the importance you may gain in the future. 

I really hope this works as it would really benefit the PHP community as a whole not just e-commerce solutions.

**Comment by mmoreram** [comment]
Hi @nyamsprod 

Thanks for you feedback, I really appreciate it :)

You're right, but right now, I am trying to join as much people related to E-commerce projects as possible, and is not easy. I know perfectly how important is finding these solutions, because is my every day, but maybe not everyone share that vision...

We can use this issue to create this list, okay?

**Comment by nyamsprod** [comment]
@mmoreram fine by me :+1:

**Comment by sagikazarmark** [comment]
This guys are doing pretty good job: https://github.com/commerceguys/

**Comment by mmoreram** [comment]
@sagikazarmark Absolutely, and because of that, they have been nicely invited to this discussion :) I think @bojanz has a lot to say and discuss here, so I hope he will join us :dancer:

**Comment by bojanz** [comment]
Thanks, I'm now here, will start commenting.

**Comment by mmoreram** [comment]
Great @bojanz , really nice to see you here :)

**Comment by sagikazarmark** [comment]
Awesome :+1:

**Comment by mmoreram** [comment]
Before creating the page of "Who we are", I would like to ping some people.
This group will not work as long as some people join us to discussions, so let's wait for some responses and then, we can decide if this group has sense. As long as it has sense, the page of all components will be published ;)

**Comment by sagikazarmark** [comment]
I think first of all you should have come up with some standards. So first you should have something AND someone.

**Comment by mmoreram** [comment]
@sagikazarmark You're absolutely right.

For that reason we've started some discussions while we ping some people :) Is that what you mean?

**Comment by sagikazarmark** [comment]
What I mean is that this group is in early phase. When it goes viral, it
should already have people and content in it.

**Comment by mmoreram** [comment]
@sagikazarmark okay :+1:  
so indeed the proposal here is just keep doing right?

**Comment by sagikazarmark** [comment]
yup ;)
